### PR TITLE
Time interval tuning, exclude magazine+POA combination

### PR DESCRIPTION
**Pull request by giorgiosironi**
- from: `00:00:00` of 6 days ago
- to: now (whenever it is sent, usually 7 pm)
- you can never publish after 7 pm or the next eToc will ignore that content
- you can send after 7 pm, or before, the only important thing is not to publish anything new for that day

Moreover, the rare magazine+POA combination:
- must appear only when becomes VOR
- must appear only in magazine section in the VOR email
- must not appear in POA email, as it stands now

### CODE REVIEW

**Review by sianroderick — APPROVED** [review]
Sounds good to me (I trust you).

**Comment by giorgiosironi** [comment]
The time passed to search need to include `H:i:s`. Have to check how well search supports them first.

**Comment by michaelmcandrew** [comment]
I am guessing that you wanted to change the time to pick up the very latest articles when the newsletter was sent out, rather than stop at midnight the day before.

My only question is are you sure that `-6 days` is correct? It feels to me like you might miss out the 'first' of the last seven days if you do that. Shouldn't it be `-7 days`?

**Comment by giorgiosironi** [comment]
The range of days is inclusive e.g. today is 2017-12-08, we collect items from 2017-12-02 (all included) to 2017-12-08 (included up to the time when eToc runs); we have specified not to publish anything after an agreed time at which we will schedule the eToc, 7pm.

**Comment by michaelmcandrew** [comment]
Makes sense. The other approach I thought of (that removes the need for an organisational policy) would be to stick with midnight to midnight but send the eToc early in the morning, say 7am. That reduces the 'lag' from 19 to 7 hours. Not sure if an early morning newsletter and that amount of lag is acceptable to you.

**Comment by giorgiosironi** [comment]
I think the time has been tuned on the US timezones, so I not easily changed.

**Review by michaelmcandrew — APPROVED** [review]

**Pull request merged**
